services:
  postgres-1:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=customers'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '15432:5432'
  postgres-2:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=products'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '15433:5432'
  postgres-3:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=orders'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '15434:5432'
